package com.omerkaya.sperrmuellfinder.domain.usecase.report

import com.omerkaya.sperrmuellfinder.core.util.Logger
import com.omerkaya.sperrmuellfinder.core.util.Result
import com.omerkaya.sperrmuellfinder.domain.model.Report
import com.omerkaya.sperrmuellfinder.domain.model.ReportPriority
import com.omerkaya.sperrmuellfinder.domain.model.ReportReason
import com.omerkaya.sperrmuellfinder.domain.model.ReportStatus
import com.omerkaya.sperrmuellfinder.domain.model.ReportTargetType
import com.omerkaya.sperrmuellfinder.domain.repository.ReportRepository
import java.util.Date
import javax.inject.Inject

/**
 * Use case for reporting content (posts, comments, users)
 * Rules.md compliant - Clean Architecture domain layer
 */
class ReportContentUseCase @Inject constructor(
    private val reportRepository: ReportRepository,
    private val logger: Logger
) {
    companion object {
        private const val TAG = "ReportContentUseCase"
        private const val MIN_DESCRIPTION_LENGTH = 10
        private const val MAX_DESCRIPTION_LENGTH = 500
    }
    
    /**
     * Report a post
     * @param postId Post to report
     * @param reason Report reason
     * @param description Optional description (min 10 chars if provided)
     * @return Result containing report ID
     */
    suspend fun reportPost(
        postId: String,
        reason: ReportReason,
        description: String? = null
    ): Result<String> {
        logger.d(TAG, "Reporting post $postId with reason ${reason.name}")
        
        // Validate description if provided
        if (description != null) {
            val validationError = validateDescription(description)
            if (validationError != null) {
                return Result.Error(Exception(validationError))
            }
        }
        
        // Check if user can report (rate limiting)
        when (val canReport = reportRepository.canUserReport(postId, ReportTargetType.POST)) {
            is Result.Success -> {
                if (!canReport.data) {
                    return Result.Error(Exception("You have already reported this content"))
                }
            }
            is Result.Error -> return canReport
            is Result.Loading -> { /* Continue */ }
        }
        
        // Calculate priority based on reason
        val priority = calculatePriority(reason)
        
        // Create report
        val report = Report(
            id = "", // Will be generated by repository
            type = ReportTargetType.POST,
            targetId = postId,
            reporterId = "", // Will be set by repository
            reporterName = "", // Will be set by repository
            reporterPhotoUrl = null,
            reason = reason,
            description = description,
            createdAt = Date(),
            status = ReportStatus.OPEN,
            priority = priority,
            assignedTo = null,
            assignedToName = null,
            adminNotes = null,
            resolvedAt = null,
            resolvedBy = null,
            resolvedByName = null,
            moderationQueueId = null,
            targetOwnerId = null,
            targetOwnerName = null,
            targetContent = null,
            targetImageUrl = null
        )
        
        return reportRepository.createReport(report)
    }
    
    /**
     * Report a comment
     * @param commentId Comment to report
     * @param reason Report reason
     * @param description Optional description
     * @return Result containing report ID
     */
    suspend fun reportComment(
        commentId: String,
        reason: ReportReason,
        description: String? = null
    ): Result<String> {
        logger.d(TAG, "Reporting comment $commentId with reason ${reason.name}")
        
        // Validate description if provided
        if (description != null) {
            val validationError = validateDescription(description)
            if (validationError != null) {
                return Result.Error(Exception(validationError))
            }
        }
        
        // Check if user can report
        when (val canReport = reportRepository.canUserReport(commentId, ReportTargetType.COMMENT)) {
            is Result.Success -> {
                if (!canReport.data) {
                    return Result.Error(Exception("You have already reported this content"))
                }
            }
            is Result.Error -> return canReport
            is Result.Loading -> { /* Continue */ }
        }
        
        // Calculate priority
        val priority = calculatePriority(reason)
        
        // Create report
        val report = Report(
            id = "",
            type = ReportTargetType.COMMENT,
            targetId = commentId,
            reporterId = "",
            reporterName = "",
            reporterPhotoUrl = null,
            reason = reason,
            description = description,
            createdAt = Date(),
            status = ReportStatus.OPEN,
            priority = priority,
            assignedTo = null,
            assignedToName = null,
            adminNotes = null,
            resolvedAt = null,
            resolvedBy = null,
            resolvedByName = null,
            moderationQueueId = null,
            targetOwnerId = null,
            targetOwnerName = null,
            targetContent = null,
            targetImageUrl = null
        )
        
        return reportRepository.createReport(report)
    }
    
    /**
     * Report a user
     * @param userId User to report
     * @param reason Report reason
     * @param description Optional description
     * @return Result containing report ID
     */
    suspend fun reportUser(
        userId: String,
        reason: ReportReason,
        description: String? = null
    ): Result<String> {
        logger.d(TAG, "Reporting user $userId with reason ${reason.name}")
        
        // Validate description if provided
        if (description != null) {
            val validationError = validateDescription(description)
            if (validationError != null) {
                return Result.Error(Exception(validationError))
            }
        }
        
        // Check if user can report
        when (val canReport = reportRepository.canUserReport(userId, ReportTargetType.USER)) {
            is Result.Success -> {
                if (!canReport.data) {
                    return Result.Error(Exception("You have already reported this user"))
                }
            }
            is Result.Error -> return canReport
            is Result.Loading -> { /* Continue */ }
        }
        
        // Calculate priority
        val priority = calculatePriority(reason)
        
        // Create report
        val report = Report(
            id = "",
            type = ReportTargetType.USER,
            targetId = userId,
            reporterId = "",
            reporterName = "",
            reporterPhotoUrl = null,
            reason = reason,
            description = description,
            createdAt = Date(),
            status = ReportStatus.OPEN,
            priority = priority,
            assignedTo = null,
            assignedToName = null,
            adminNotes = null,
            resolvedAt = null,
            resolvedBy = null,
            resolvedByName = null,
            moderationQueueId = null,
            targetOwnerId = null,
            targetOwnerName = null,
            targetContent = null,
            targetImageUrl = null
        )
        
        return reportRepository.createReport(report)
    }
    
    /**
     * Validate description text
     */
    private fun validateDescription(description: String): String? {
        return when {
            description.isBlank() -> "Description cannot be empty"
            description.length < MIN_DESCRIPTION_LENGTH -> 
                "Description must be at least $MIN_DESCRIPTION_LENGTH characters"
            description.length > MAX_DESCRIPTION_LENGTH -> 
                "Description must not exceed $MAX_DESCRIPTION_LENGTH characters"
            else -> null
        }
    }
    
    /**
     * Calculate priority based on report reason
     * SPAM and HARASSMENT are HIGH priority
     * Others are MEDIUM priority
     */
    private fun calculatePriority(reason: ReportReason): ReportPriority {
        return when (reason) {
            ReportReason.SPAM,
            ReportReason.HARASSMENT,
            ReportReason.DANGEROUS_GOODS -> ReportPriority.HIGH
            ReportReason.INAPPROPRIATE_CONTENT,
            ReportReason.SCAM -> ReportPriority.MEDIUM
            else -> ReportPriority.LOW
        }
    }
}
